name: Backend Chat CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t hello-world-app .
      - name: Tags
        run: |
          docker tag hello-world-app ${{ secrets.DOCKER_USER }}/back:${{ github.sha }}
          docker tag hello-world-app ${{ secrets.DOCKER_USER }}/back:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/hello-world-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/hello-world-app:latest